#!/bin/bash

echo "🚀 Deploy InkFlow CRM su Vercel"
echo ""
echo "Passi da seguire:"
echo ""
echo "1. Vai su: https://vercel.com/new"
echo "2. Clicca su 'Import Project'"
echo "3. Seleziona 'Import Git Repository' o 'Deploy from CLI'"
echo "4. Se usi Git:"
echo "   - Collega GitHub"
echo "   - Seleziona questo repository"
echo "   - Vercel rileverà automaticamente Vite"
echo "   - Clicca 'Deploy'"
echo ""
echo "5. Se usi CLI:"
echo "   - Esegui: npx vercel --prod"
echo "   - Segui le istruzioni"
echo ""
echo "La cartella 'dist' è già pronta per il deploy!"
echo ""
echo "📁 Build directory: dist/"
echo "🔧 Build command: npm run build"
echo "⚙️  Framework: Vite"
